# Generated by Django 5.0 on 2026-04-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('papas', 'Papas'), ('adiciones', 'Adiciones'), ('salsas', 'Salsas'), ('bebidas', 'Bebidas'), ('hamburguesa', 'Hamburguesa'), ('arepa', 'Arepa'), ('perro', 'Perro Caliente'), ('pizza', 'Pizza'), ('bebida', 'Bebida'), ('postre', 'Postre'), ('otro', 'Otro')], max_length=50),
        ),
    ]
