# Generated by Django 5.0 on 2026-04-02 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_venta_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_nombre',
            field=models.CharField(default='Cliente', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_orden',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['numero_orden'], name='tienda_vent_numero__8c759e_idx'),
        ),
    ]
