# Generated by Django 5.0 on 2026-04-02 21:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_cierrecaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución')], max_length=20)),
                ('tipo_entrada', models.CharField(blank=True, choices=[('compra', 'Compra'), ('devolucion', 'Devolución de Cliente'), ('transferencia_entrada', 'Transferencia Recibida'), ('otro', 'Otro')], max_length=50, null=True)),
                ('tipo_salida', models.CharField(blank=True, choices=[('venta', 'Venta'), ('merma', 'Merma'), ('consumo_interno', 'Consumo Interno'), ('transferencia_salida', 'Transferencia Enviada'), ('otro', 'Otro')], max_length=50, null=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_anterior', models.PositiveIntegerField(default=0)),
                ('stock_posterior', models.PositiveIntegerField(default=0)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tienda.producto')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='tienda.tienda')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
                'indexes': [models.Index(fields=['tienda', 'fecha_movimiento'], name='tienda_movi_tienda__c622f4_idx'), models.Index(fields=['producto', 'fecha_movimiento'], name='tienda_movi_product_fed134_idx'), models.Index(fields=['tipo_movimiento'], name='tienda_movi_tipo_mo_6947a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='tienda.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='tienda.tienda')),
            ],
            options={
                'verbose_name_plural': 'Stocks Actuales',
                'ordering': ['producto__categoria', 'producto__nombre'],
                'indexes': [models.Index(fields=['tienda', 'producto'], name='tienda_stoc_tienda__12ea70_idx'), models.Index(fields=['cantidad'], name='tienda_stoc_cantida_9d17b7_idx')],
                'unique_together': {('tienda', 'producto')},
            },
        ),
    ]
