# Generated by Django 5.0 on 2026-04-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_movimientoinventario_stockactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('papas', 'Papas'), ('adiciones', 'Adiciones'), ('salsas', 'Salsas'), ('bebidas', 'Bebidas'), ('hamburguesa', 'Hamburguesa'), ('arepa', 'Arepa'), ('perro', 'Perro Caliente'), ('pizza', 'Pizza'), ('bebida', 'Bebida'), ('postre', 'Postre'), ('ingrediente_base', 'Ingrediente Base'), ('proteinas', 'Proteínas'), ('vegetales', 'Vegetales'), ('aderezos', 'Aderezos'), ('complemento', 'Complemento'), ('otro', 'Otro')], max_length=50),
        ),
    ]
